### ISSUE TITLE
Add matrix problems

### ISSUE THREAD

**Issue by theakhiljha** [theakhiljha/Ultimate-Logic#5]
Create a new folder of Matrix problems and add questions with solution in different languages

- Python
- Java
- C++
- C
- C#
- PHP

or any language of your choice.

**Comment by ikamalrawal** [comment]
assign it pls.

**Comment by Kartik987** [comment]
hey @theakhiljha . Can i contribute to this?

**Comment by theakhiljha** [comment]
@Kartik987 yeah sure go ahead ! just make sure you aren't copying anyone else code.

**Comment by cdeepanshu** [comment]
I have make the PR please check it and merge it

**Comment by Kartik987** [comment]
I have just make a PR. Please review and merge it.

**Comment by psymbio** [comment]
Hey @theakhiljha can I contribute to this the following:

+ adding dynamic matrices
+ multiplying dynamic matrices
+ ceaser cipher
+ linear equation solving through matrices
+ finding the largest element

**Comment by theakhiljha** [comment]
@cdeepanshu @Kartik987 ah ! cool

**Comment by theakhiljha** [comment]
@psymbio yeah sure just take care of folders

**Comment by psymbio** [comment]
Yeah, sure will do.

I'll add them in by tomorrow.

**Comment by theakhiljha** [comment]
@psymbio okay cool

**Comment by thevyanshu** [comment]
Can I contribute to this in python

**Comment by kratikasinghal** [comment]
hey! @theakhiljha Can I work on this?

**Comment by harshitgupta2000** [comment]
@theakhiljha i want to contribute please assign me the multiplication or transpose  of 3x3 matrix in C or python

**Comment by theakhiljha** [comment]
> Hi @theakhiljha, can I work on the algorithm to print all elements of a matrix in spiral order given a matrix of m x n elements (m rows, n columns)?

Sure! Go ahead

**Comment by theakhiljha** [comment]
> Hi @theakhiljha, can I work on the algorithm to print all elements of a matrix in spiral order given a matrix of m x n elements (m rows, n columns)?

@samkit96 sure! Go ahead

**Comment by theakhiljha** [comment]
> hey! @theakhiljha Can I work on this?

@kratikasinghal yes

**Comment by theakhiljha** [comment]
> Can I contribute to this in python
> 
@thevyanshu yes

**Comment by cdeepanshu** [comment]
@theakhiljha I have added one more proagram to matrix folder please review it and merge

**Comment by titichhm** [comment]
@theakhiljha I would like to add two leetcode medium questions. The solutions are mine and coded in C++. Can I add them?

**Comment by theakhiljha** [comment]
@titichhm yes sure just take care of folder

**Comment by titichhm** [comment]
@theakhiljha I have added two questions. Please review the PR. Thanks :)

**Comment by titichhm** [comment]
I added two programs a day before. Please review the PR and merge it if there are no issues. Thanks : )
