### ISSUE TITLE
Create Sorting & Searching problems

### ISSUE THREAD

**Issue by theakhiljha** [theakhiljha/Ultimate-Logic#6]
Create a new folder of Sorting & Searching problems and add question with solution in different languages

- Python
- Java
- C++
- C
- C#
- PHP

or any language of your choice.

**Comment by ikamalrawal** [comment]
Assign it pls

**Comment by padmaja-22** [comment]
Can I contribute?

**Comment by theakhiljha** [comment]
@padmaja-22 yes sure go ahead !

**Comment by padmaja-22** [comment]
Can I add a separate folder for searching algorithms? like the program of linear search in different languages in that folder?

**Comment by NidhiNivedita6** [comment]
Can I do binary search in C?

**Comment by Mayankjha997** [comment]
Can I add binary search in C++?

**Comment by Kartik987** [comment]
I have just created a PR with sorting folder and code for insertion sort in c++. Please check and it.

**Comment by padmaja-22** [comment]
I created a folder and a PR. Can u please review and merge

**Comment by theakhiljha** [comment]
@NidhiNivedita6 @Mayankjha997 sure !

**Comment by theakhiljha** [comment]
@padmaja-22 okay cool

**Comment by theakhiljha** [comment]
@Kartik987 great let me check

**Comment by ParthPali** [comment]
Hey @theakhiljha , can I do bubble sorting in Java.

**Comment by ParthPali** [comment]
@theakhiljha I created a PR, please review.

**Comment by Pratyushraj2121** [comment]
I have created a PR which includes both searching and sorting in C. Please Check!

**Comment by SubhamChoudhury** [comment]
Can I contribute to this repo?

**Comment by harshitgupta2000** [comment]
I want to do quick or merge sort please assign it to me for any of the 3 languages(python,C or C++)

**Comment by Mayankjha997** [comment]
please check @theakhiljha and merge my PR  #13
Thanks!
